#!/usr/bin/env python
"""
Renumber the scans in an .ms2 file. Sometimes I seem to end up with ms2 files with
all the scans having scan number 0.
"""

import argparse
import logging
from datetime import datetime
from pyvalise.io import ms2_io

__author__ = "Damon May"
__copyright__ = "Copyright (c) 2015 Damon May"
__license__ = ""
__version__ = ""

logger = logging.getLogger(__name__)


def renumber_scans(scans):
    scan_number = 1
    for scan in scans:
        scan.scan_number = scan_number
        scan_number += 1
        yield scan


def main():

    # declare args
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('infile', type=argparse.FileType('r'),
                        help='input file')
    parser.add_argument('--out', type=argparse.FileType('w'), required=True,
                        help='output file')
    parser.add_argument('--debug', action="store_true", help='Enable debug logging')
    args = parser.parse_args()

    # logging
    logging.basicConfig(level=logging.INFO, 
                        format="%(asctime)s %(levelname)s: %(message)s")
    if args.debug:
        logger.setLevel(logging.DEBUG)
    ms2_io.write_ms2(renumber_scans(ms2_io.read_ms2_scans(args.infile)),
                     args.out)
    print("Done.")




start_time = datetime.now()
logger.debug("Start time: %s" % start_time)
main()
logger.debug("End time: %s" % datetime.now())
logger.debug("Elapsed time: %s" % (datetime.now() - start_time))
